language: csharp
os:
  - linux
  - osx
osx_image: xcode8.3
solution: IEMod.pw.sln
mono: latest
dist: trusty
sudo: required
dotnet: 2.1.1

before_install:
  - msbuild /version

install:
  - dotnet restore

script:
  - dotnet --info
  - dotnet restore
  - dotnet build --no-restore -c Release /v:m /p:Configuration=Release -f net45
